//This is the code file for the surplus mining crate, a 3500 point unlocked necropolis crate miners can buy with spare points.
/obj/structure/closet/crate/necropolis/surplus
	name = "surplus necropolis chest"
	desc = "A dusty, old necropolis crate, from some deep space science warehouse. It has a big orange sticker that reads <b> Quality Not Guaranteed </b>"
	icon_state = "necrocrate"
	resistance_flags = LAVA_PROOF | FIRE_PROOF | ACID_PROOF
	can_install_electronics = FALSE

/obj/structure/closet/crate/necropolis/surplus/PopulateContents()
	var/loot = rand(1,100)
	switch(loot)
		if(1,2) //
			new /obj/item/shared_storage/red(src)
		if(3,4)
			new /obj/item/soulstone/anybody/mining(src)
		if(5,6)
			new /obj/item/clothing/neck/cloak/wolf_coat(src) //Wolf Coat from icebox demonic portal drop table, because we dont have icebox on, so may as well add some extra goodies here. After all the crate costs 5k points which is quite a bit.
		if(7,8)
			new /obj/item/clothing/glasses/godeye(src)
		if(9,10)
			new /obj/item/reagent_containers/cup/bottle/potion/flight(src)
		if(11,12)
			new /obj/item/clothing/gloves/gauntlets(src)
		if(13,14)
			new /obj/item/clothing/glasses/hud/health/night/meson(src) //Night vision health mesons, a handy little tool for shaft miners who are focused on combat or dont want god eye!
		if(15,16)
			new /obj/item/rod_of_asclepius(src)
		if(17,18)
			new /obj/item/organ/heart/cursed/wizard(src)
		if(19,20)
			new /obj/item/ship_in_a_bottle(src)
		if(21,22)
			new /obj/item/clothing/suit/hooded/berserker(src)
		if(23,24)
			new /obj/item/jacobs_ladder(src)
		if(25,26)
			new /obj/item/kinetic_crusher/runic_greatsword(src) //A crusher made by the catgirls on icebox, does a marking swing around it instead of firing a destabilizing shot
		if(27,28)
			new /obj/item/warp_cube/red(src)
		if(29,30)
			new /obj/item/wisp_lantern(src)
		if(31,32)
			new /obj/item/immortality_talisman(src)
		if(33,34)
			new /obj/item/book/granter/action/spell/summonitem(src)
		if(35,36)
			new /obj/item/book_of_babel(src)
		if(37,38)
			new /obj/effect/spawner/random/mining_loot/pka_mod(src)
		if(39,40)
			new /obj/item/clothing/neck/necklace/memento_mori(src)
		if(41,42,43) //Junk drops start here ----
			new /obj/item/disk/nuclear/fake/obvious(src)
			new /obj/item/toy/figure/syndie(src)
			new /obj/item/toy/figure/syndie(src)
			new /obj/item/toy/figure/syndie(src)
			new /obj/item/toy/figure/syndie(src)
			new /obj/item/toy/nuke(src)
			new /obj/item/toy/balloon/syndicate(src)
			new /obj/item/storage/backpack/duffelbag/syndie/interdyne/maidkit_sing(src) //armor at the cost of your pride, a fair trade for some miners.
		if(44,45,46)
			new /obj/item/clothing/gloves/maid_arm_covers(src)
			new /obj/item/clothing/head/costume/maid_headband(src)
			new /obj/item/clothing/shoes/laceup(src)
			new /obj/item/clothing/under/costume/maid(src)
			new /obj/structure/sign/poster/official/no_erp(src)
			new /obj/item/slimepotion/lovepotion(src)
		if(47,48,49)
			new /obj/structure/spider/cocoon(src)
			new /obj/item/dnainjector/webbing(src)
			new /obj/structure/spider/stickyweb(src)
			new /mob/living/basic/spider/maintenance(src)
			new /mob/living/basic/spider/maintenance(src)
			new /mob/living/basic/spider/maintenance(src)
		if(50,51,52)
			new /obj/effect/decal/cleanable/garbage(src)
			new /obj/item/storage/pill_bottle/maintenance_pill/full(src)
			new /obj/item/trash/syndi_cakes(src)
			new /obj/item/paper/crumpled(src)
			new /obj/item/trash/popcorn(src)
			new /obj/item/trash/can/food/peaches/maint(src)
			new /obj/item/storage/cans(src)
			new /obj/item/book/granter/crafting_recipe/dusting/pipegun_prime(src)
			new /obj/item/book/granter/crafting_recipe/dusting/laser_musket_prime(src)
			new /obj/item/book/granter/crafting_recipe/dusting/smoothbore_disabler_prime(src)
			new /obj/item/book/granter/crafting_recipe/trash_cannon(src)
		if(53,54,55)
			new /obj/item/toy/crayon/spraycan/lubecan(src)
			new /obj/item/pillow/clown(src)
			new /obj/item/megaphone/clown(src)
			new /obj/item/grown/bananapeel(src)
		if(56,57,58)
			new /obj/item/clothing/head/costume/kitty(src)
			new /obj/item/clothing/under/costume/seifuku(src)
			new /obj/item/clothing/neck/petcollar(src)
			new /mob/living/basic/pet/cat(src)
			new /obj/item/toy/cattoy(src)
			new /obj/item/slimepotion/sentience(src)
		if(59,60,61)
			new /mob/living/basic/pet/dog/corgi/puppy(src)
			new /mob/living/basic/pet/dog/corgi/exoticcorgi(src)
			new /mob/living/basic/pet/dog/corgi/lisa(src)
			new /obj/structure/sign/poster/quirk/service_logo(src)
			new /obj/item/toy/balloon/corgi(src)
			new /obj/item/clothing/suit/hooded/ian_costume(src)
			new /obj/item/dnainjector/olfaction(src)
		if(62,63,64)
			new /obj/item/seeds/banana(src)
			new /obj/item/food/grown/banana(src)
			new /obj/item/food/grown/banana(src)
			new /obj/item/food/grown/banana(src)
			new /obj/item/food/grown/banana(src)
			new /obj/item/food/grown/banana(src)
			new /obj/item/dnainjector/h2m(src)
		if(65,66,67)
			new /obj/item/pickaxe/rusted(src)
			new /obj/item/pickaxe/rusted(src)
			new /obj/item/pickaxe/rusted(src)
			new /obj/item/pickaxe/rusted(src)
			new /obj/item/dnainjector/dwarf(src)
			new /obj/item/dnainjector/dwarf(src)
			new /obj/item/dnainjector/dwarf(src)
			new /obj/item/dnainjector/dwarf(src)
			new /obj/structure/closet/crate/miningcar(src)
		if(68,69,70)
			new /obj/item/gun/ballistic/rifle/boltaction(src)
			new /obj/item/clothing/head/costume/ushanka(src)
			new /obj/item/reagent_containers/cup/glass/bottle/vodka/badminka(src)
			new /obj/item/clothing/under/costume/soviet(src)
		if(71,72,73)
			new /obj/item/instrument/piano_synth/headphones/spacepods(src)
			new /obj/item/clothing/shoes/swagshoes(src)
			new /obj/item/clothing/under/costume/swagoutfit(src)
			new /obj/item/clothing/neck/necklace/dope(src)
		if(74,75,76)
			for(var/index in 1 to 50)
				new /obj/item/stack/ore/slag(src)
		if(77,78,79)
			new /obj/item/storage/belt/military/snack(src)
			new /obj/item/knife/combat(src)
			new /obj/item/clothing/gloves/color/black(src)
			new /obj/item/clothing/under/rank/centcom/military/eng(src)
			new /obj/item/clothing/suit/armor/vest/old(src)
		if(80,81,82) //fuck you get a key - nanotrasen
			new /obj/structure/closet/crate/necropolis/tendril(src)
		if(83) // The rare drops start here ---- the bonus loot for risking 5k points
			new /obj/item/crusher_trophy/bear_paw(src)
		if(84)
			new /obj/item/crusher_trophy/wolf_ear(src)
		if(85)
			new /obj/item/gun/ballistic/revolver/govmining/venator(src) //The Sister's gift
		if(86)
			new /obj/item/gun/ballistic/shotgun/automatic/combat/compact/goliathhunter(src) //The Brother's gift
		if(87)
			new /obj/item/huntermagicbook(src) //hunter magic granter
		if(88)
			new /obj/item/book/granter/action/spell/smoke/lesser(src)
			new /obj/item/book/granter/chuunibyou(src)
			new /obj/item/book/granter/action/spell/summon_cheese(src)
		if(89)
			new /obj/item/crusher_trophy/legionnaire_spine(src)
		if(90)
			new /obj/item/clothing/accessory/pandora_hope(src)
		if(91)
			new /obj/item/crusher_trophy/broodmother_tongue(src)
		if(92)
			new /obj/item/clothing/neck/cloak/herald_cloak(src)
		if(93) //kaboom :>
			new /obj/item/toy/plush/ratplush(src)
			new /obj/item/toy/plush/narplush(src)
		if(94)
			new /obj/item/crusher_trophy/ice_demon_cube(src) //Good icebox trophy
		if(96)
			new /mob/living/simple_animal/hostile/asteroid/elite/broodmother_child(src)
		if(95)
			new /obj/item/seeds/gelthi(src) //cool seeds
			new /obj/item/seeds/jurlmah(src)
			new /obj/item/seeds/shand(src)
			new /obj/item/seeds/surik(src)
			new /obj/item/seeds/telriis(src)
			new /obj/item/seeds/thaadra(src)
			new /obj/item/seeds/vaporsac(src)
		if(97)
			new /obj/item/crusher_trophy/ice_block_talisman(src) //This is a good trophy from icebox, so we are offering it here.
		if(98)
			new /obj/item/stack/ore/diamond(src, 50)
			new /obj/item/stack/ore/bluespace_crystal(src, 50)
			new /obj/item/stack/ore/bananium(src, 50)
		if(99) //100,000 CREDIT JACKPOT
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
			new /obj/item/stack/spacecash/c10000(src)
		if(100) //Jackpot
			new /obj/item/storage/backpack/holding(src)
